K fold cross validation is used to find out best performing algorithm on dataset 
or say it measures performance of algorithm

In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

In [2]:
from sklearn.model_selection import train_test_split
x_train,x_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size = 0.3)

In [3]:
lr = LogisticRegression()
lr.fit(x_train,y_train)
lr.score(x_test, y_test)

C:\Users\dell\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9648148148148148

In [4]:
svm =  SVC()
svm.fit(x_train,y_train)
svm.score(x_test, y_test)

0.9833333333333333

In [5]:
rf =  RandomForestClassifier(n_estimators=40)
rf.fit(x_train,y_train)
rf.score(x_test,y_test)

0.9666666666666667

**Using K fold **

In [6]:
from sklearn.model_selection import KFold
kf = KFold(n_splits = 3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [7]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
  print('train_set ->', train_index,'test_set->',test_index)

train_set -> [3 4 5 6 7 8] test_set-> [0 1 2]
train_set -> [0 1 2 6 7 8] test_set-> [3 4 5]
train_set -> [0 1 2 3 4 5] test_set-> [6 7 8]


In [8]:
def get_score(model, x_train, x_test, y_train, y_test):
    
    model.fit(x_train, y_train)
    return model.score(x_test, y_test)


In [9]:
get_score(LogisticRegression(), x_train, x_test, y_train, y_test)

C:\Users\dell\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9648148148148148

In [10]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits = 3)

In [11]:
scores_l = []
scores_svm = []
score_rf = []

for train_index, test_index in kf.split(digits.data):
      X_train,X_test, Y_train, Y_test = digits.data[train_index], digits.data[test_index],digits.target[train_index], digits.target[test_index]
      scores_l.append(get_score(LogisticRegression(),X_train,X_test,Y_train,Y_test))
      scores_svm.append(get_score(SVC(),X_train,X_test,Y_train,Y_test))
      score_rf.append(get_score(RandomForestClassifier(),X_train,X_test,Y_train,Y_test))

C:\Users\dell\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\dell\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i 

In [12]:
scores_l

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [13]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [14]:
score_rf

[0.9365609348914858, 0.9616026711185309, 0.9332220367278798]

CROSS VAL SCORE METHOD is same code as above function 

In [15]:
from sklearn.model_selection import cross_val_score

In [16]:
cross_val_score(LogisticRegression(), digits.data, digits.target)

C:\Users\dell\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\dell\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i 

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [17]:
cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [18]:
cross_val_score(RandomForestClassifier(), digits.data, digits.target)

array([0.92222222, 0.91944444, 0.95264624, 0.97214485, 0.91922006])