In [1]:
import numpy as np

In [2]:
X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y = np.array([[0,1,1,0]]).T
X.shape, Y.shape

((4, 2), (4, 1))

In [4]:
def sig(z):
    return 1/(1+ np.exp(-z))

In [5]:
def derivativeSig(z):
    return sig(z)* (1-sig(z))

In [6]:
# one hidden layer weights
wh = 2 * np.random.random((2,2)) - 1
bh = 2 * np.random.random((1,2)) - 1
wo = 2 * np.random.random((2,1)) - 1
bo = 2 * np.random.random((1,1)) - 1
lr = 0.1

In [21]:
# forward propagation with one hidden layer
for iter in range(10000):
    output0 = X
    inputHidden = np.dot(output0, wh) + bh
    outputHidden = sig(inputHidden)
    inputForOutputLayer = (np.dot(outputHidden, wo) + bo)
    output = sig(inputForOutputLayer)
    
    firstTermForOutputLayer = output - Y
    secondTermForOutputLayer = derivativeSig(inputForOutputLayer)
    first_two_output_layer=firstTermForOutputLayer*secondTermForOutputLayer
    first_term_hidden_layer = np.dot(first_two_output_layer, wo.T)
    second_term_hidden_layer = derivativeSig(inputHidden)
    first_two_hidden_layer = first_term_hidden_layer * second_term_hidden_layer

    changes_output = np.dot(output0.T, first_two_output_layer)
    changes_output_bias = np.sum(first_two_output_layer, axis = 0, keepdims = True)

    changes_hidden = np.dot(output0.T, first_two_hidden_layer)
    changes_hidden_bias = np.sum(first_two_hidden_layer, axis = 0, keepdims = True)

    wo = wo - lr*changes_output
    bo =  bo-lr* changes_output_bias

    wh = wh - lr*changes_hidden
    bh =  bh-lr* changes_hidden_bias


output0 = X
inputHidden = np.dot(output0, wh) + bh
outputHidden = sig(inputHidden)
inputForOutputLayer = (np.dot(outputHidden, wo) + bo)
output = sig(inputForOutputLayer)
output, wh, bh, wo, bo

(array([[0.02850203],
        [0.9597481 ],
        [0.99118664],
        [0.02432672]]),
 array([[ 5.49134847,  4.42595409],
        [-5.41287452, -4.88890848]]),
 array([[ 2.49206098, -3.70701504]]),
 array([[-8.05253652],
        [13.67049755]]),
 array([[3.58074723]]))